name: vkr_regatta
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  path_drawing: ^1.0.1
  dio: ^5.9.0
  retrofit: ^4.7.2
  json_annotation: ^4.11.0
  flutter_secure_storage: ^9.2.4
  cupertino_icons: ^1.0.8
  drift: ^2.32.1
  archive: ^4.0.7
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.5
  path: ^1.9.1
  regatta_sensor_bridge:
    path: packages/regatta_sensor_bridge

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  json_serializable: ^6.11.1
  retrofit_generator: ^10.1.2
  drift_dev: ^2.32.1

flutter:
  uses-material-design: true
